# fly.toml app configuration file generated for dailydigestai on 2025-02-23T14:28:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dailydigestai'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
